# Generated by Django 5.0 on 2024-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crorde', models.CharField(max_length=50, null=True)),
                ('transitionid', models.IntegerField(max_length='10', null=True)),
                ('amount', models.IntegerField(max_length='100', null=True)),
                ('ledgerhead', models.CharField(max_length=100, null=True)),
                ('onoroff', models.CharField(max_length=50, null=True)),
                ('accounttype', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
